dist: bionic
language: C
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa     
  - sudo apt-get update     
  - sudo apt-get install gcc-arm-embedded

jobs:
  include:
    -name: "build"
    script:
      bash ci/makeall.csh
